import { TypingSVGOptions } from '@/types/options';

export interface TextTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  options: Partial<TypingSVGOptions>;
}

export const textTemplates: TextTemplate[] = [
  {
    id: 'developer-title',
    name: 'Developer Title',
    description: 'Professional developer title with common tech stack',
    category: 'Professional',
    options: {
      lines: ['Full Stack Developer', 'React & Node.js', 'Open Source Enthusiast'],
      font: 'Fira Code',
      size: 20,
      color: '#36BCF7',
      center: true,
      width: 400,
      height: 50,
    },
  },
  {
    id: 'social-links',
    name: 'Social Links',
    description: 'Display your social media presence',
    category: 'Social',
    options: {
      lines: ['Follow me on Twitter', 'Check out my GitHub', 'Connect on LinkedIn'],
      font: 'Roboto',
      size: 18,
      color: '#00ADB5',
      center: true,
      width: 350,
      height: 50,
    },
  },
  {
    id: 'skills',
    name: 'Tech Skills',
    description: 'Showcase your technical skills',
    category: 'Professional',
    options: {
      lines: ['JavaScript / TypeScript', 'React / Vue / Angular', 'Node.js / Python / Go'],
      font: 'JetBrains Mono',
      size: 18,
      color: '#2E8B57',
      center: true,
      width: 400,
      height: 60,
      multiline: true,
    },
  },
  {
    id: 'student',
    name: 'Student Profile',
    description: 'For students and learners',
    category: 'Education',
    options: {
      lines: ['Computer Science Student', 'Aspiring Software Engineer', 'Always Learning'],
      font: 'Poppins',
      size: 20,
      color: '#FF6B6B',
      center: true,
      width: 380,
      height: 50,
    },
  },
  {
    id: 'freelancer',
    name: 'Freelancer',
    description: 'Available for freelance work',
    category: 'Professional',
    options: {
      lines: ['Freelance Developer', 'Available for Hire', 'Let\'s Work Together'],
      font: 'Montserrat',
      size: 20,
      color: '#9B59B6',
      center: true,
      width: 380,
      height: 50,
    },
  },
  {
    id: 'gaming',
    name: 'Gaming Profile',
    description: 'For gaming enthusiasts',
    category: 'Gaming',
    options: {
      lines: ['Pro Gamer', 'Twitch Streamer', 'FPS Champion'],
      font: 'Press Start 2P',
      size: 16,
      color: '#00FF00',
      background: '#1a1a2e',
      center: true,
      width: 400,
      height: 50,
    },
  },
  {
    id: 'designer',
    name: 'Designer',
    description: 'For UI/UX designers',
    category: 'Design',
    options: {
      lines: ['UI/UX Designer', 'Creating Beautiful Interfaces', 'Design Systems Enthusiast'],
      font: 'Playfair Display',
      size: 20,
      color: '#E91E63',
      center: true,
      width: 420,
      height: 50,
    },
  },
  {
    id: 'quotes',
    name: 'Inspirational Quotes',
    description: 'Motivational programming quotes',
    category: 'Quotes',
    options: {
      lines: ['Code is poetry', 'Make it work, make it right, make it fast', 'Talk is cheap. Show me the code'],
      font: 'Fira Code',
      size: 18,
      color: '#FFD700',
      center: true,
      width: 450,
      height: 50,
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean and minimal style',
    category: 'Style',
    options: {
      lines: ['Hello World', 'Welcome to my profile'],
      font: 'Inter',
      size: 22,
      color: '#333333',
      center: true,
      width: 350,
      height: 45,
    },
  },
  {
    id: 'gradient-vibes',
    name: 'Gradient Vibes',
    description: 'Modern gradient style',
    category: 'Style',
    options: {
      lines: ['Building the Future', 'One Line at a Time'],
      font: 'Poppins',
      size: 22,
      gradient: true,
      gradientFrom: '#667eea',
      gradientTo: '#764ba2',
      center: true,
      width: 380,
      height: 50,
    },
  },
  {
    id: 'cto',
    name: 'CTO Profile',
    description: 'For Chief Technology Officers',
    category: 'Professional',
    options: {
      lines: ['Chief Technology Officer', 'Leading Innovation', 'Building Scalable Systems'],
      font: 'Fira Code',
      size: 20,
      color: '#0066CC',
      center: true,
      width: 420,
      height: 50,
    },
  },
  {
    id: 'devops',
    name: 'DevOps Engineer',
    description: 'For DevOps professionals',
    category: 'Professional',
    options: {
      lines: ['DevOps Engineer', 'CI/CD Expert', 'Cloud Infrastructure Specialist'],
      font: 'JetBrains Mono',
      size: 18,
      color: '#FF6600',
      center: true,
      width: 450,
      height: 60,
      multiline: true,
    },
  },
  {
    id: 'data-scientist',
    name: 'Data Scientist',
    description: 'For data science professionals',
    category: 'Professional',
    options: {
      lines: ['Data Scientist', 'Machine Learning Engineer', 'Turning Data into Insights'],
      font: 'Roboto',
      size: 20,
      color: '#00CED1',
      center: true,
      width: 420,
      height: 50,
    },
  },
  {
    id: 'blog',
    name: 'Blog Profile',
    description: 'For bloggers and content creators',
    category: 'Social',
    options: {
      lines: ['Tech Blogger', 'Writing About Code', 'Read My Latest Posts'],
      font: 'Poppins',
      size: 20,
      color: '#FF8C00',
      center: true,
      width: 400,
      height: 50,
    },
  },
  {
    id: 'portfolio',
    name: 'Portfolio',
    description: 'For showcasing your work',
    category: 'Social',
    options: {
      lines: ['View My Portfolio', 'Recent Projects', 'Let\'s Create Something Amazing'],
      font: 'Montserrat',
      size: 20,
      color: '#6C5CE7',
      center: true,
      width: 400,
      height: 50,
    },
  },
  {
    id: 'newsletter',
    name: 'Newsletter',
    description: 'For newsletter creators',
    category: 'Social',
    options: {
      lines: ['Subscribe to My Newsletter', 'Weekly Tech Insights', 'Join 10K+ Readers'],
      font: 'Inter',
      size: 18,
      color: '#0984E3',
      center: true,
      width: 420,
      height: 60,
      multiline: true,
    },
  },
  {
    id: 'bootcamp-grad',
    name: 'Bootcamp Graduate',
    description: 'For bootcamp graduates',
    category: 'Education',
    options: {
      lines: ['Bootcamp Graduate', 'Full Stack Developer', 'Ready to Make an Impact'],
      font: 'Fira Code',
      size: 20,
      color: '#E17055',
      center: true,
      width: 400,
      height: 50,
    },
  },
  {
    id: 'researcher',
    name: 'Researcher',
    description: 'For academic researchers',
    category: 'Education',
    options: {
      lines: ['CS Researcher', 'PhD Candidate', 'Exploring New Frontiers'],
      font: 'Roboto',
      size: 20,
      color: '#2D3436',
      center: true,
      width: 380,
      height: 50,
    },
  },
  {
    id: 'teacher',
    name: 'Teacher',
    description: 'For coding instructors',
    category: 'Education',
    options: {
      lines: ['Coding Instructor', 'Teaching the Next Generation', 'Making Code Accessible'],
      font: 'Poppins',
      size: 20,
      color: '#00B894',
      center: true,
      width: 400,
      height: 50,
    },
  },
  {
    id: 'game-dev',
    name: 'Game Developer',
    description: 'For game developers',
    category: 'Gaming',
    options: {
      lines: ['Game Developer', 'Unity & Unreal', 'Creating Immersive Worlds'],
      font: 'Press Start 2P',
      size: 16,
      color: '#FF006E',
      background: '#16213E',
      center: true,
      width: 420,
      height: 60,
      multiline: true,
    },
  },
  {
    id: 'speedrunner',
    name: 'Speedrunner',
    description: 'For speedrunners',
    category: 'Gaming',
    options: {
      lines: ['Speedrunner', 'Any% WR Holder', 'Glitch Hunter'],
      font: 'Press Start 2P',
      size: 14,
      color: '#FFD700',
      background: '#0F0F0F',
      center: true,
      width: 380,
      height: 60,
      multiline: true,
    },
  },
  {
    id: 'graphic-designer',
    name: 'Graphic Designer',
    description: 'For graphic designers',
    category: 'Design',
    options: {
      lines: ['Graphic Designer', 'Visual Storyteller', 'Brand Identity Specialist'],
      font: 'Playfair Display',
      size: 20,
      color: '#E84393',
      center: true,
      width: 420,
      height: 50,
    },
  },
  {
    id: 'motion-designer',
    name: 'Motion Designer',
    description: 'For motion graphics designers',
    category: 'Design',
    options: {
      lines: ['Motion Designer', 'Animation Enthusiast', 'Bringing Ideas to Life'],
      font: 'Montserrat',
      size: 20,
      color: '#6C5CE7',
      center: true,
      width: 400,
      height: 50,
    },
  },
  {
    id: 'philosophical',
    name: 'Philosophical Quotes',
    description: 'Deep programming wisdom',
    category: 'Quotes',
    options: {
      lines: ['First, solve the problem', 'Then, write the code', 'Simplicity is the ultimate sophistication'],
      font: 'Fira Code',
      size: 18,
      color: '#74B9FF',
      center: true,
      width: 450,
      height: 60,
      multiline: true,
    },
  },
  {
    id: 'humorous',
    name: 'Humorous Quotes',
    description: 'Funny programming quotes',
    category: 'Quotes',
    options: {
      lines: ['99 little bugs in the code', '99 little bugs', 'Take one down, patch it around', '127 little bugs in the code'],
      font: 'JetBrains Mono',
      size: 16,
      color: '#FD79A8',
      center: true,
      width: 400,
      height: 80,
      multiline: true,
    },
  },
  {
    id: 'neon',
    name: 'Neon Glow',
    description: 'Cyberpunk neon style',
    category: 'Style',
    options: {
      lines: ['NEON DREAMS', 'CYBERPUNK VIBES'],
      font: 'Orbitron',
      size: 24,
      color: '#00FFFF',
      background: '#0D0D0D',
      center: true,
      width: 400,
      height: 60,
    },
  },
  {
    id: 'retro',
    name: 'Retro Terminal',
    description: 'Classic terminal style',
    category: 'Style',
    options: {
      lines: ['> INITIALIZING...', '> LOADING...', '> READY'],
      font: 'Fira Code',
      size: 18,
      color: '#00FF00',
      background: '#000000',
      center: false,
      width: 350,
      height: 70,
      multiline: true,
    },
  },
  {
    id: 'elegant',
    name: 'Elegant Serif',
    description: 'Elegant serif typography',
    category: 'Style',
    options: {
      lines: ['Crafting Digital Experiences', 'With Passion & Precision'],
      font: 'Playfair Display',
      size: 22,
      color: '#2C3E50',
      center: true,
      width: 450,
      height: 50,
    },
  },
  {
    id: 'startup-founder',
    name: 'Startup Founder',
    description: 'For startup entrepreneurs',
    category: 'Business',
    options: {
      lines: ['Startup Founder', 'Building the Next Big Thing', ' disrupting Industries'],
      font: 'Inter',
      size: 20,
      color: '#00D4FF',
      center: true,
      width: 420,
      height: 50,
    },
  },
  {
    id: 'consultant',
    name: 'Consultant',
    description: 'For technical consultants',
    category: 'Business',
    options: {
      lines: ['Technical Consultant', 'Helping Businesses Scale', 'Digital Transformation Expert'],
      font: 'Roboto',
      size: 20,
      color: '#2E86AB',
      center: true,
      width: 420,
      height: 50,
    },
  },
  {
    id: 'product-manager',
    name: 'Product Manager',
    description: 'For product managers',
    category: 'Business',
    options: {
      lines: ['Product Manager', 'User-Centric Design', 'Data-Driven Decisions'],
      font: 'Poppins',
      size: 20,
      color: '#FF6B6B',
      center: true,
      width: 400,
      height: 50,
    },
  },
  {
    id: 'writer',
    name: 'Technical Writer',
    description: 'For technical writers',
    category: 'Creative',
    options: {
      lines: ['Technical Writer', 'Documenting the Future', 'Making Tech Accessible'],
      font: 'Merriweather',
      size: 20,
      color: '#4A5568',
      center: true,
      width: 420,
      height: 50,
    },
  },
  {
    id: 'photographer',
    name: 'Photographer',
    description: 'For photographers',
    category: 'Creative',
    options: {
      lines: ['Photographer', 'Capturing Moments', 'Visual Storyteller'],
      font: 'Playfair Display',
      size: 22,
      color: '#2D3436',
      center: true,
      width: 380,
      height: 50,
    },
  },
  {
    id: 'musician',
    name: 'Musician',
    description: 'For musicians',
    category: 'Creative',
    options: {
      lines: ['Musician & Developer', 'Code by Day, Music by Night', 'Harmonizing Creativity'],
      font: 'Montserrat',
      size: 20,
      color: '#E84393',
      center: true,
      width: 420,
      height: 50,
    },
  },
  {
    id: 'mobile-dev',
    name: 'Mobile Developer',
    description: 'For mobile app developers',
    category: 'Tech',
    options: {
      lines: ['Mobile Developer', 'iOS & Android', 'Building Apps for Everyone'],
      font: 'Fira Code',
      size: 20,
      color: '#007AFF',
      center: true,
      width: 400,
      height: 50,
    },
  },
  {
    id: 'ai-engineer',
    name: 'AI Engineer',
    description: 'For AI/ML engineers',
    category: 'Tech',
    options: {
      lines: ['AI Engineer', 'Deep Learning Specialist', 'Building Intelligent Systems'],
      font: 'JetBrains Mono',
      size: 18,
      color: '#9B59B6',
      center: true,
      width: 420,
      height: 60,
      multiline: true,
    },
  },
  {
    id: 'blockchain',
    name: 'Blockchain Developer',
    description: 'For blockchain developers',
    category: 'Tech',
    options: {
      lines: ['Blockchain Developer', 'Web3 Enthusiast', 'Building the Decentralized Future'],
      font: 'Fira Code',
      size: 18,
      color: '#F7931A',
      center: true,
      width: 450,
      height: 60,
      multiline: true,
    },
  },
  {
    id: 'personal-blog',
    name: 'Personal Blog',
    description: 'For personal blogs',
    category: 'Personal',
    options: {
      lines: ['My Personal Blog', 'Thoughts & Experiences', 'Life Through Code'],
      font: 'Merriweather',
      size: 20,
      color: '#2C3E50',
      center: true,
      width: 400,
      height: 50,
    },
  },
  {
    id: 'about-me',
    name: 'About Me',
    description: 'Personal introduction',
    category: 'Personal',
    options: {
      lines: ['Hi, I\'m [Your Name]', 'A Passionate Developer', 'Based in [Your City]'],
      font: 'Poppins',
      size: 20,
      color: '#3498DB',
      center: true,
      width: 400,
      height: 60,
      multiline: true,
    },
  },
  {
    id: 'contact-info',
    name: 'Contact Info',
    description: 'Contact information display',
    category: 'Personal',
    options: {
      lines: ['Get in Touch', 'email@example.com', 'github.com/username'],
      font: 'Roboto',
      size: 18,
      color: '#27AE60',
      center: true,
      width: 380,
      height: 70,
      multiline: true,
    },
  },
  {
    id: 'open-source',
    name: 'Open Source',
    description: 'For open source contributors',
    category: 'Tech',
    options: {
      lines: ['Open Source Contributor', 'Building for the Community', 'Code Available on GitHub'],
      font: 'Fira Code',
      size: 18,
      color: '#6CC24A',
      center: true,
      width: 450,
      height: 60,
      multiline: true,
    },
  },
  {
    id: 'cloud-architect',
    name: 'Cloud Architect',
    description: 'For cloud architects',
    category: 'Tech',
    options: {
      lines: ['Cloud Architect', 'AWS | Azure | GCP', 'Designing Scalable Solutions'],
      font: 'JetBrains Mono',
      size: 18,
      color: '#FF9900',
      center: true,
      width: 420,
      height: 60,
      multiline: true,
    },
  },
  {
    id: 'security-expert',
    name: 'Security Expert',
    description: 'For cybersecurity professionals',
    category: 'Tech',
    options: {
      lines: ['Security Engineer', 'Penetration Tester', 'Protecting Digital Assets'],
      font: 'Fira Code',
      size: 18,
      color: '#E74C3C',
      center: true,
      width: 400,
      height: 60,
      multiline: true,
    },
  },
  {
    id: 'pastel',
    name: 'Pastel Dreams',
    description: 'Soft pastel color scheme',
    category: 'Style',
    options: {
      lines: ['Dreamy Pastels', 'Soft & Serene'],
      font: 'Quicksand',
      size: 24,
      color: '#FFB6C1',
      center: true,
      width: 380,
      height: 60,
    },
  },
  {
    id: 'monochrome',
    name: 'Monochrome',
    description: 'Clean black and white style',
    category: 'Style',
    options: {
      lines: ['SIMPLE. CLEAN. BOLD.', 'MONOCHROME AESTHETIC'],
      font: 'Inter',
      size: 22,
      color: '#000000',
      center: true,
      width: 400,
      height: 60,
    },
  },
  {
    id: 'sunset',
    name: 'Sunset Gradient',
    description: 'Warm sunset gradient style',
    category: 'Style',
    options: {
      lines: ['Chasing Sunsets', 'Golden Hour Vibes'],
      font: 'Poppins',
      size: 22,
      gradient: true,
      gradientFrom: '#FF512F',
      gradientTo: '#DD2476',
      center: true,
      width: 400,
      height: 50,
    },
  },
  {
    id: 'ocean',
    name: 'Ocean Waves',
    description: 'Cool ocean gradient style',
    category: 'Style',
    options: {
      lines: ['Ocean Breeze', 'Deep Blue Dreams'],
      font: 'Montserrat',
      size: 22,
      gradient: true,
      gradientFrom: '#2193b0',
      gradientTo: '#6dd5ed',
      center: true,
      width: 380,
      height: 50,
    },
  },
  {
    id: 'matrix',
    name: 'Matrix Style',
    description: 'The Matrix digital rain style',
    category: 'Style',
    options: {
      lines: ['WAKE UP, NEO...', 'THE MATRIX HAS YOU...', 'FOLLOW THE WHITE RABBIT'],
      font: 'Fira Code',
      size: 16,
      color: '#00FF00',
      background: '#000000',
      center: false,
      width: 400,
      height: 80,
      multiline: true,
    },
  },
];

export const templateCategories = Array.from(
  new Set(textTemplates.map(t => t.category))
);
